version: '3'

services:
  prototype:
    build:
      context: .
    ports:
      - "3000:3000"
    image: dit/investment-projects-prototype
    environment:
      REDIS_URL: 'redis://redis:6379'
    links:
      - redis

  redis:
    image: redis

